<h2>Purchase Overview</h2>
<?php
$vou = $inp->value_pgd('id');;
$query_recept = sprintf("SELECT recipt FROM purchase_recipt WHERE idpurchase = '%s'", $vou);
$recept = $qur->get_custom_select_query($query_recept, 1);
$query_pro = sprintf("SELECT idproduct, p.unite, rate, name, mesurment_unite.unite FROM (SELECT idproduct, unite, rate, name FROM (SELECT idproduct,unite,rate FROM purchase_details WHERE idpurchase = %d) as purchase LEFT JOIN product USING (idproduct)) as p LEFT JOIN product_details USING(idproduct) LEFT JOIN mesurment_unite USING(idunite);", $vou);
$sell_pro = $qur->get_custom_select_query($query_pro, 5);
$query_det = sprintf("SELECT name,date,discount FROM (SELECT * FROM purchase s WHERE idpurchase = %d) as purchase LEFT JOIN purchase_discount USING (idpurchase) LEFT JOIN party USING (idparty);", $vou);
$sell_det = $qur->get_custom_select_query($query_det, 3);
$n = count($sell_pro);
echo "Supplier Voucher : <b>" . $recept[0][0] . "</b>";
echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Purchased From : ";
echo "<b class='blue'>" . $sell_det[0][0] . "</b>";
echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On date : ";
echo "<b class='blue'>" . $inp->date_convert($sell_det[0][1]) . "</b>";
echo "<br/><br>";
echo "<table class='rb' align='center'>";
echo "<tr>";
echo "<th>";
echo "SI";
echo "</th>";
echo "<th>";
echo "Product";
echo "</th>";
echo "<th>";
echo "Quantity";
echo "</th>";
echo "<th>";
echo "Rate";
echo "</th>";
echo "<th>";
echo "Total";
echo "</th>";
echo "</tr>";
$charges_total = 0;
for ($j = 0; $j < $n; $j++) {
    echo "<tr>";
    echo "<td>" . ($j + 1) . "</td>";
    echo "<td>";
    echo esc($sell_pro[$j][3]);
    echo "</td>";
    echo "<td>";
    echo esc($sell_pro[$j][1]);
    echo " ";
    echo esc($sell_pro[$j][4]);
    echo "</td>";
    echo "<td class='text-right'>";
    echo money($sell_pro[$j][2]);
    echo "</td>";
    echo "<td class='text-right'>";
    $mul = $sell_pro[$j][1] * $sell_pro[$j][2];
    echo money($mul);
    $charges_total = $charges_total + $mul;
    echo "</td>";
    echo "</tr>";
}
echo "<tr>";
echo "<th colspan='4'class='text-right'>";
echo "Total Charges:";
echo "</th>";
echo "<th class='text-right'>";
echo money($charges_total);
echo "</th>";
echo "</tr>";
echo "<tr>";
echo "<th colspan='4' class='text-right'>";
echo "Discount:";
echo "</th>";
echo "<th class='text-right'>";
echo money($sell_det[0][2]);
echo "</th>";
echo "</tr>";
echo "<tr>";
echo "<th colspan='4' class='text-right'>";
echo "Net charges:";
echo "</th>";
echo "<th class='text-right'>";
$net = $charges_total - $sell_det[0][2];
echo money($net);
echo "</th>";
echo "</tr>";
echo "</table>";